stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/raw.csv


  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/raw.csv
    outs:
      - artifacts/data_validation/status.txt


  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data_ingestion/raw.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv


  training:
    cmd: python src/mlProject/pipeline/stage_04_model_training.py
    deps:
      - src/mlProject/pipeline/stage_04_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/raw.csv
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
    params:
      - alpha
      - l1_ratio
      # - BATCH_SIZE
      # - AUGMENTATION
    outs:
      - artifacts/model_trainer/model.joblib


  evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/raw.csv
      - artifacts/model_trainer/model.joblib
    params:
      - alpha
      - l1_ratio
    outs:
    - artifacts/model_evaluation/metrics.json