artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/raw.csv  # for saving location and type

  # source_URL: https://github.com/maheshpachpande/Branching-tutorial/raw/master/winequality-data.zip
  # local_data_file: artifacts/data_ingestion/data.zip
  # unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/raw.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/raw.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib  # in which format model save